ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"
ansible_pass: "{{ vault_ansible_pass }}"
ansible_become_pass: "{{ vault_ansible_pass }}"

vlan:
  network: "10.0.0.0"
  gateway: "10.0.0.1"

system:
  default_interface: #dynamic
  interfaces:
    - eth0
    - eth1
    - eth2
    - eth3

  storage:
    device: sda

kolla:
  # When an OpenStack cloud is deployed, each services’ REST API is presented
  # as a series of endpoints. These endpoints are the admin URL, the internal URL,
  # and the external URL. Kolla offers separate options of assigning these endpoints
  # to network addresses. External URL is assigned to an IP address that is
  # different than the IP address shared by the internal and admin URLs.
  # kolla_internal_vip_address, for INTERNAL trafic of REST API edpoint services
  vip_internal: # should not be pingable, dont have to set interface
    address:  "{{ vlan.network | set_subnet(10) }}"

  # kolla_external_vip_address, for EXTERNAL trafic of REST API edpoint services
  vip_external: # should not be pingable, dont have to set interface
    address: "{{ vlan.network | set_subnet(15) }}"

# /home/openstack/kolla/globals.yml
openstack:

  install_type: 'binary' # binary, source (more reliable)
  release: 'train'

  interface: # dynamic

  node: # dynamic, all-in-one
  nodes: # dynamic, multinode
    control:
    network:
    compute:
    monitoring:
    storage:

  storage:
    cinder:
      device: sdb
      number: 1

  # The management network carries API traffic between the OpenStack servers,
  # as well as message queue, database etc. traffic. In a two-network configuration,
  # it probably also carries VM traffic over GRE or VXLAN tunnels, and
  # external API traffic. In short, everything except public traffic.
  management:
    interface: # dynamic, neutron_internal_interface (network_interface)
    address: "{{ vlan.network | set_subnet(20) }}"
    vid: 20
  # The public interface connects the node to a public network, such as an
  # external network. This gives instances connectivity to the outside world.
  public:
    interface: # dynamic, neutron_external_interface
    address:  "{{ vlan.network | set_subnet(25) }}"
    vid: 25

  virtual_router_subnet: "30"

  # /home/openstack/venv/python2.7/share/kolla-ansible/init-runonce
  ext_net:
    cidr: '{{ vlan.network }}/24'  # This will become public
    range: # These range of addresses will be floating IPs
      start: "{{ vlan.network | set_subnet(100) }}"
      end: "{{ vlan.network | set_subnet(200) }}"
    gateway: '{{ vlan.gateway }}'

