---
- name: Build wrapper for kolla-ansible init-runonce
  vars:
    dest: '{{ kolla_ansible_init_runonce_path }}'
  block:
    - debug:
        msg: dest is {{ dest }}
    - name: "Make sure {{ dest }} exists and is empty."
      file:
        path: '{{ dest }}'
        state: '{{ item }}'
      with_items:
        - absent
        - touch
    - lineinfile:
        line: "#!/usr/bin/env bash"
        path: "{{ dest }}"
        create: yes
    - lineinfile:
        line: source {{ venv_path }}/bin/activate
        path: "{{ dest }}"
    - lineinfile:
        line: source {{ kolla_config_dir }}/admin-openrc.sh
        path: "{{ dest }}"
    - blockinfile:
        marker: "# {mark} ANSIBLE MANAGED BLOCK --> ENV VARIABLES"
        create: yes
        path: "{{ dest }}"
        block: |2
          echo "Export env variables"
          set -e
          export ANSIBLE_CONFIG='{{ kolla_config_dir }}/ansible.cfg'
          export KOLLA_CONFIG_PATH='{{ kolla_config_dir }}'
          export ANSIBLE_INVENTORY='{{ kolla_config_dir }}/multinode'
          export ANSIBLE_HOST_KEY_CHECKING=False
          export ENABLE_EXT_NET=1
          export EXT_NET_CIDR={{ openstack.ext_net.cidr }}
          export EXT_NET_RANGE=start={{ openstack.ext_net.range.start }},end={{ openstack.ext_net.range.end }}
          export EXT_NET_GATEWAY={{ openstack.ext_net.gateway }}

    - include: wrapper.yml
      vars:
        exec: 'pip'
        args: 'install python-openstackclient'
        kwargs:

    - include: wrapper.yml
      vars:
        exec: 'bash'
        args: '{{ kolla_ansible_init_runonce_exec }}'
        kwargs:
