---
- name: "Execute 'ssh' task to generate and authorize keys"
  block:
    - debug:
        msg: Check ssh-create variables
      failed_when: |
        local_user is not defined
        or local_ssh_path is not defined
        or ssh_key is not defined

    - name: "Make ssh key locally"
      openssh_keypair:
        path: '{{ local_ssh_path }}/{{ item }}'
        state: present
      with_items:
        - '{{ ssh_key }}'
      register: out

    - name: "Touch authorized_keys"
      file:
        path: '{{ local_ssh_path }}/authorized_keys'
        state: file
        mode: 'u+rw,g-wx,o-rwx'

    - name: "Authorize key"
      authorized_key:
        user: "{{ local_user }}"
        key: "{{ item }}"
        state: present
        path: '{{ local_ssh_path }}/authorized_keys'
        comment: "Ansible key for OPENSTACK"
        manage_dir: yes
      with_file:
        - '{{ local_ssh_path }}/{{ ssh_key }}.pub'

