

- name: Parse template kolla_globals.yml.j2 to {{ kolla_config_dir }}/globals.yml
  template:
    src: kolla/vars/globals.yml.j2
    dest: '{{ kolla_config_dir }}/globals.yml'
  with_items:
    - {
        kolla_base_distro: '{{ system.base_distro }}',
        kolla_install_type: '{{  openstack.install_type }}',
        openstack_release: '{{ openstack.release }}',
        kolla_internal_vip_address: '{{ kolla.vip_internal.address }}',
        kolla_external_vip_address: '{{ kolla.vip_external.address }}',
        neutron_internal_interface: '{{ openstack.management.interface }}',
        neutron_external_interface: '{{ openstack.public.interface }}',
        keepalived_virtual_router_id: '{{ openstack.virtual_router_subnet }}'
      }
  register: out
- debug: var=out
  tags: debug
