- name: Setup kolla passwords.yml if not exists
  vars:
    condition:
  block:
    - name: Check that the {{ kolla_config_dir }}/passwords.yml exists
      stat:
        path: '{{ kolla_config_dir }}/passwords.yml'
      register: condition
    - debug: var=condition
      tags: debug

    - name: Copy passwords.yml to {{ kolla_config_dir }}/passwords.yml
      copy:
        src: kolla/vars/passwords.yml
        dest: '{{ kolla_config_dir }}/passwords.yml'
        owner: '{{ superuser }}'
        group: '{{ superuser }}'
      when: condition.stat.exists == False
    - debug: var=condition
      tags: debug

#    - name: which kolla-genpwd
#      shell:
#        cmd: which kolla-genpwd
#        chdir: '{{ superuser_home }}'
#        executable: "{{ venv_path }}/bin/bashvenv"
#      register: kollaGenpwdPath
#
#    - set_fact:
#        kolla_genpwd: '{{ kollaGenpwdPath.stdout_lines | first }}'
#
#    - name: Kolla passwords
#      shell:
#        cmd: '{{ kolla_genpwd }} --passwords {{ kolla_config_dir }}/passwords.yml'
#        chdir: '{{ superuser_home }}'
#        executable: "{{ venv_path }}/bin/bashvenv"
#      register: out
#
#    - debug: var=out
#      tags: debug
